package utils;

public enum TokenType {
    IDENTIFIER, NUMBER, ASSIGNMENT, REL_OP, MATH_OP, FLOAT, R_PARENTHESIS, L_PARENTHESIS,
    ALGORITMO, DECLARACOES, INTEIRO, REAL, INPUT, IF, THEN, ELSE, ASSIGN, TO, AND, OR,
    PRINT, WHILE, DO, ENDWHILE, FOR, FROM, STEP, UNTIL, ENDFOR, SEMICOLON, COLON, CADEIA,END_ALGORITMO;
}
